### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by denisnarush** [kaktuxis/Resto#4]
```
@font-face {
    font-family: Aleo-Regular;
    src: url(Aleo-Regular.otf); 
   }
```

ты подключил только один шрифт, надо еще 3 Aleo и 1 другой шрифт подключить.
Причем это строка `font-family: Aleo-Regular;` в секции `@font-face` отвечает за то как шрифт будет использоваться.

**Comment by miraslaupats** [comment]
Выполнено
